[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SlimeVRX/SlimeVRX/blob/main/d2l/code/2.3.ipynb)

In [1]:
import numpy as np

1. Chứng minh rằng chuyển vị của một ma trận chuyển vị là chính nó:  (A⊤)⊤=A .
```
Chứng minh:
A⊤ = [A⊤]ij = [A]ji
(A⊤)⊤ = ([A]ji)⊤ = [A⊤]ji = [A]ij = A
```

2. Cho hai ma trận A và B , chứng minh rằng tổng của chuyển vị bằng chuyển vị của tổng: A⊤+B⊤=(A+B)⊤ .
```
Chứng minh: A⊤ + B⊤ = (A+B)⊤
A⊤ + B⊤ = [A⊤]ij + [B⊤]ij = [A]ji + [B]ji = [A+B]ji
(A + B)⊤ = ([A]ij + [B]ij)⊤ = [A+B]ijT = [A+B]ji
suy ra A⊤ + B⊤ = (A + B)⊤
```

3. Cho một ma trận vuông A , liệu rằng A+A⊤ có luôn đối xứng? Tại sao?
```
Chứng minh:
Anew[i,j] = A[i,j] + A⊤[i,j] = A[i,j] + A[j,i]
Anew[j,i] = A[j,i] + A⊤[j,i] = A[j,i] + A[i,j]
suy ra: Anew[i,j] = Anew[j,i] nên A+A⊤ luôn đối xứng
```

4. Chúng ta đã định nghĩa tensor X với kích thước ( 2 , 3 , 4 ) trong mục này. Kết quả của len(X) là gì?
```
len(X) = 2
```

In [9]:
a = np.arange(6).reshape(3, 2)
X = np.arange(24).reshape(2, 3, 4)

In [10]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
len(a)

3

In [12]:
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [13]:
len(X)

2

5. Cho một tensor X với kích thước bất kỳ, liệu len(X) có luôn tương ứng với độ dài của một trục nhất định của X hay không? Đó là trục nào?
```
axis=0
tham khảo link: https://www.sharpsightlabs.com/blog/numpy-axes-explained/
```

6. Chạy A / A.sum(axis=1) và xem điều gì xảy ra. Bạn có phân tích được nguyên nhân không?
```
Lỗi
```

In [15]:
A = np.arange(12).reshape(3, 4)

In [16]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
len(A)

3

In [23]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [20]:
A/A.sum(axis=1)

ValueError: ignored

7. Khi di chuyển giữa hai điểm ở Manhattan (đường phố hình bàn cờ), khoảng cách tính bằng tọa độ (tức độ dài các đại lộ và phố) mà bạn cần di chuyển là bao nhiêu? Bạn có thể đi theo đường chéo không? (Xem thêm bản đồ Manhattan, New York để trả lời câu hỏi này)
```
Không thể đi theo đường chéo, di chuyển theo trục X, Y.
```


8. Xét một tensor với kích thước ( 2 ,  3 ,  4 ). Kích thước của kết quả sau khi tính tổng theo trục  0 ,  1  và  2  sẽ như thế nào?

In [24]:
X = np.arange(24).reshape(2, 3, 4)

In [25]:
X

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
X.sum(axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [30]:
X.sum(axis=1)

array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [32]:
X.sum(axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

9. Đưa một tensor với 3 trục hoặc hơn vào hàm linalg.norm và quan sát kết quả. Hàm này thực hiện việc gì cho các ndarray với kích thước bất kỳ?

In [41]:
Y = np.arange(3).reshape(3)

In [42]:
Y

array([0, 1, 2])

In [43]:
np.linalg.norm(Y)

2.23606797749979

In [46]:
np.sqrt(1**2+ 2**2)

2.23606797749979

In [54]:
X = np.arange(8).reshape(2,2,2)

In [55]:
X

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
np.linalg.norm(X)

11.832159566199232

In [56]:
np.sqrt(1**2+ 2**2+ 3**2 + 4**2 + 5**2 + 6**2 + 7**2)

11.832159566199232