[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SlimeVRX/SlimeVRX/blob/main/hipnuc/document/06_1.ipynb)

## Study [Attitude determination for IMU & AHRS](https://zhuanlan.zhihu.com/p/351596374) 
#**Lesson 06_1: Prove the formula Antisymmetric matrix.**

In [ ]:
import numpy as np
from numpy.linalg import norm

sin = np.sin
cos = np.cos

In [ ]:
def Euler_Rodrigues(M,theta):
    dim = M.shape[0]
    I = np.eye(dim)
    MLG = I + sin(theta)*M + (1-cos(theta))*np.matmul(M,M)
    return MLG

In [ ]:
def ch_askew(v):
    m = np.array([[0,     -v[2],   v[1]],
                  [v[2],   0,     -v[0]],
                  [-v[1],   v[0],   0]], dtype=np.float64)
    return m

In [ ]:
M = np.array([[0, -1, 0],
              [1, 0, 0],
              [0, 0, 0]])
theta = 30
Euler_Rodrigues(M,np.deg2rad(theta))

array([[ 0.8660254, -0.5      ,  0.       ],
       [ 0.5      ,  0.8660254,  0.       ],
       [ 0.       ,  0.       ,  1.       ]])

In [ ]:
# M = np.array([0.6781005, 0.6392788, 0.36263249])
M = np.array([0.6096,  0.5747, 0.3260])
theta = 30
Euler_Rodrigues(ch_askew(M),np.deg2rad(theta))

array([[ 0.94151257, -0.11606373,  0.31397472],
       [ 0.20993627,  0.93597513, -0.27969956],
       [-0.26072528,  0.32990044,  0.90596427]])

In [ ]:
V = np.array([0, 0, 1])
n = norm(V,2)
# R = np.identity(3) + (sin(n)/n) * ch_askew(V) + ((1-cos(n)) / (n**2)) * (ch_askew(V).dot(ch_askew(V)))
R = np.identity(3) + (sin(n)/n) * ch_askew(V) + ((1-cos(n)) / (n**2)) * np.matmul(ch_askew(V), ch_askew(V))
print(R)

[[ 0.54030231 -0.84147098  0.        ]
 [ 0.84147098  0.54030231  0.        ]
 [ 0.          0.          1.        ]]


In [ ]:
ch_askew([0,0,1])

array([[ 0., -1.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [ ]:
rv = np.array([0, 0, 1])
phi = norm(rv,2)
u = rv / phi
print("Rotation Vector (RV):\n", rv)
print("The axis of rotation is: (Unit vector)\n", u)
print("The rotation angle: %f deg\n" %(np.rad2deg(phi)))

Rotation Vector (RV):
 [0 0 1]
The axis of rotation is: (Unit vector)
 [0. 0. 1.]
The rotation angle: 57.295780 deg

