[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SlimeVRX/SlimeVRX/blob/main/hipnuc/document/07.ipynb)

#**Study [Attitude for IMU & AHRS](https://zhuanlan.zhihu.com/p/351596374)**
#**Lesson 07: Quaternion** [(四元数)](https://zhuanlan.zhihu.com/p/60301874)

Ma trận Attitude sử dụng 9 tham số để biểu thị, trong khi không gian 3D chỉ có 3 bậc tự do. Quaternion sử dụng 4 tham số để biểu thị Attitude nhỏ gọn và hiệu quả hơn. Quaternion rất quan trọng. Trong chương trình thực của chúng tôi, chúng tôi không sử dụng góc Euler cho các phép toán Attitude, và hiếm khi sử dụng ma trận quay. Về cơ bản, chúng tôi sử dụng Quaternion.

### Khái niệm Quaternion
Biết được Axis-Angle thì khái niệm Quaternion rất dễ giới thiệu:

<p align="left"><img width="200", src="https://pic3.zhimg.com/80/v2-61ef01bdddc381c169bc0eb6f252381e_720w.jpg"></p>

Trong số đó Pi là góc trong Axis-Angle, và u là vectơ Axis (trục) trong  Axis-Angle, phần trước (cos) là phần vô hướng w (hoặc được gọi q0), phần sau (sin) là phần vectơ (v) x, y, z hoặc được gọi là (q1, q2, q3)

<p align="left"><img width="300", src="https://pic1.zhimg.com/80/v2-1459ad61d2ab466e19526aedef530b20_720w.png"></p>

Định nghĩa cơ bản của quaternion, q0 là phần vô hướng, q1, q2, q3 là phần vectơ

i,j k thỏa:

<p align="left"><img width="300", src="https://pic1.zhimg.com/80/v2-f3f79ccbfd81fb29c5b2f50d37356590_720w.png"></p>

Các Quaternion có một số thuộc tính quan trọng: (Các thuộc tính của quaternion hoàn toàn giống với ma trận quay (ma trận trực giao))
- Đơn vị Quaternion có thể đại diện cho Attitude, tương ứng với ma trận xoay một-một(rotation matrix one-to-one). Tất cả các mảng Attitude có cùng thuộc tính với Quaternion: ví dụ, AB != BA, không thỏa mãn tính kết hợp.
- Phép liên hợp của Quaternion đơn vị có cùng kết quả với phép nghịch đảo, đó là phủ định vectơ (negate the vector part)
- Nói tóm lại, các thuộc tính của Quaternion và mảng Attitude tương ứng một-một, hay Quaternion là "nén thông tin" của mảng Attitude. Bản chất là như nhau.

Đặc biệt lưu ý:
- Một số phương pháp biểu diễn đặt phần vô hướng ở trước và một số khác đặt ở cuối, hãy chú ý để phân biệt. Do đó, Quaternion thường được viết là

<p align="left"><img width="150", src="https://www.zhihu.com/equation?tex=%5Cbegin%7Bbmatrix%7D+w%26x%26y%26z%5Cend%7Bbmatrix%7D"></p>

hoặc

<p align="left"><img width="150", src="https://www.zhihu.com/equation?tex=%5Cbegin%7Bbmatrix%7D+x%26y%26z%26w%5Cend%7Bbmatrix%7D"></p>

trong hầu hết các trường hợp là wxyz.
- Có hai định nghĩa về Quaternion: Quaternion Hamilton (được sử dụng trong loạt bài này thường được sử dụng) và Quaternion JPL. Một phần của tài liệu sử dụng Quaternion JPL, hãy chú ý.

### Một số hoạt động quan trọng trên Quaternion
- Chuẩn hóa: (tức là đơn nhất hóa) Chỉ cần một đơn vị Quaternion là có thể đại diện cho Attitude! (Mặc định, Quaternion đề cập đến Quaternion đơn vị).

<p align="left"><img width="150", src="https://www.zhihu.com/equation?tex=q%5E%7B-1%7D%3Dq%5E%7B%5Cstar%7D+%2F%7Cq%7C%5E%7B2%7D"></p>

- Liên hợp: Phần vô hướng không thay đổi, phần vectơ là nghịch đảo và Quaternion liên hợp đơn vị biểu thị sự quay ngược lại của Quaternion đơn vị ban đầu.

<p align="left"><img width="350", src="https://www.zhihu.com/equation?tex=q%5E%7B%5Cstar%7D%3Dq_%7B0%7D-q%3Dq_%7B0%7D-i+q_%7B1%7D-j+q_%7B2%7D-k+q_%7B3%7D"></p>

- Phép nhân Quaternion (phép nội suy, phép nhân Quaternion không có tính giao hoán, phép toán quan trọng nhất):

<p align="left"><img width="450", src="https://pic3.zhimg.com/80/v2-527ffcffc4373f550ebc6713b5415f7e_720w.png"></p>

Viết dưới dạng ma trận:

<p align="left"><img width="500", src="https://pic2.zhimg.com/80/v2-263e87cff41e2bfa7be052fb2b6c5799_720w.jpg"></p>

hoặc:

<p align="left"><img width="300", src="https://pic3.zhimg.com/80/v2-4f9df04bef6ae80e2aeadebf54e5ab9e_720w.jpg"></p>

Phép nhân các Quaternion cũng giống như phép nhân các mảng Attitude, cả hai đều thể hiện sự chồng chất của phép quay, nhưng chỉ có phép nhân các Quaternion đơn vị mới có ý nghĩa vật lý như vậy!

- Mảng Quaternion-to-pose:

<p align="left"><img width="500", src="https://pic4.zhimg.com/80/v2-f9c9a75e03bb569ca23700a93ba69bb3_720w.jpg"></p>

- Attitude Array Quaternion:

<p align="left"><img width="500", src="https://pic2.zhimg.com/80/v2-12286140b2a4e9efc65319ff4670786d_720w.jpg"></p>

Để biết được các công thức này, vui lòng tham khảo sách giáo khoa của Giáo viên Yan Gongmin. Sau khi viết rất nhiều công thức, hãy nhanh chóng biến tất cả chúng thành các hàm của thư viện Python: từ bây giờ, chúng ta sẽ bao gồm Quaternion trong gói. (Các chức năng thư viện này đều sử dụng lại các chức năng hộp công cụ của ông Yan Gongmin)



In [1]:
import numpy as np
from numpy.linalg import norm   #norm(V,2)


In [2]:
def ch_qconj(qin):
    return np.concatenate([[qin[0]], -qin[1:]])

def ch_qnormlz(q):
    q = q / norm(q,2)
    if q[0] < 0:
        q[0] = -q[0]
        q[1] = -q[1]
        q[2] = -q[2]
        q[3] = -q[3]
    return q

def ch_qmul(q1, q2):
    q = np.array([ q1[0] * q2[0] - q1[1] * q2[1] - q1[2] * q2[2] - q1[3] * q2[3],
                   q1[0] * q2[1] + q1[1] * q2[0] + q1[2] * q2[3] - q1[3] * q2[2],
                   q1[0] * q2[2] + q1[2] * q2[0] + q1[3] * q2[1] - q1[1] * q2[3],
                   q1[0] * q2[3] + q1[3] * q2[0] + q1[1] * q2[2] - q1[2] * q2[1] ], dtype=np.float64)
    return q

def ch_q2m(Qb2n):
    q11 = Qb2n[0]*Qb2n[0]; q12 = Qb2n[0]*Qb2n[1]; q13 = Qb2n[0]*Qb2n[2]; q14 = Qb2n[0]*Qb2n[3]
    q22 = Qb2n[1]*Qb2n[1]; q23 = Qb2n[1]*Qb2n[2]; q24 = Qb2n[1]*Qb2n[3]
    q33 = Qb2n[2]*Qb2n[2]; q34 = Qb2n[2]*Qb2n[3]
    q44 = Qb2n[3]*Qb2n[3]
    Cb2n = np.array([[ q11+q22-q33-q44,  2*(q23-q14),     2*(q24+q13)],
                     [2*(q23+q14),      q11-q22+q33-q44, 2*(q34-q12)],
                     [2*(q24-q13),      2*(q34+q12),     q11-q22-q33+q44 ]], dtype=np.float64)
    return Cb2n

def ch_m2q(Cb2n):
    C11 = Cb2n[0,0]; C12 = Cb2n[0,1]; C13 = Cb2n[0,2]
    C21 = Cb2n[1,0]; C22 = Cb2n[1,1]; C23 = Cb2n[1,2]
    C31 = Cb2n[2,0]; C32 = Cb2n[2,1]; C33 = Cb2n[2,2]

    if C11 >= C22+C33:
        q1 = 0.5*np.sqrt(1+C11-C22-C33)
        q0 = (C32-C23)/(4*q1); q2 = (C12+C21)/(4*q1); q3 = (C13+C31)/(4*q1)
    elif C22>= C11+C33:
        q2 = 0.5*np.sqrt(1-C11+C22-C33)
        q0 = (C13-C31)/(4*q2); q1 = (C12+C21)/(4*q2); q3 = (C23+C32)/(4*q2)
    elif C33>=C11+C22:
        q3 = 0.5*np.sqrt(1-C11-C22+C33)
        q0 = (C21-C12)/(4*q3); q1 = (C13+C31)/(4*q3); q2 = (C23+C32)/(4*q3)
    else:
        q0 = 0.5*np.sqrt(1+C11+C22+C33)
        q1 = (C32-C23)/(4*q0); q2 = (C13-C31)/(4*q0); q3 = (C21-C12)/(4*q0)
    Qb2n = np.array([q0, q1, q2, q3], dtype=np.float64)
    return Qb2n

In [3]:
Qb2n = np.array([0.981, 0.010, -0.191, 0.011])
Cb2n = ch_q2m(Qb2n)
print("Quaternion Qb2n to Attitude Array Cb2n:\n", Cb2n)

Qb2n = ch_m2q(Cb2n)
print("Attitude array Cb2n to Quaternion Qb2n:\n", Qb2n)

Quaternion Qb2n to Attitude Array Cb2n:
 [[ 0.925859 -0.025402 -0.374522]
 [ 0.017762  0.998621 -0.023822]
 [ 0.374962  0.015418  0.925901]]
Attitude array Cb2n to Quaternion Qb2n:
 [ 0.98111939  0.00999878 -0.19097676  0.01099866]


### Phép nhân Quaternion và vectơ 3D (Xoay 3D bằng cách sử dụng Quaternion)

Điều này tương đương với việc nhân ma trận Attitude với một vectơ ba chiều, tương đương với việc quay vectơ ba chiều theo một góc, ngoại trừ ma trận Attitude được sử dụng trước đó, lần này được xoay bởi Quaternion:

Mở rộng một vectơ ba chiều ... trở thành một Quaternion ... :

<p align="left"><img width="30", src="https://www.zhihu.com/equation?tex=r%5E%7Bb%7D"></p>

<p align="left"><img width="70", src="https://www.zhihu.com/equation?tex=%5Cleft%5B%5Cbegin%7Barray%7D%7Bc%7D+0+%5C%5C+%5Cboldsymbol%7Br%7D%5E%7Bb%7D+%5Cend%7Barray%7D%5Cright%5D"></p>

Xoay 3D sử dụng Quaternion:

<p align="left"><img width="400", src="https://pic3.zhimg.com/80/v2-71d411a47f6dcc8a715bce24d8ac805e_720w.png"></p>

hay:

<p align="left"><img width="150", src="https://pic3.zhimg.com/80/v2-83b72eaf515e2da8ad82d6c3b387cb9e_720w.png"></p>

Ý nghĩa của toán tử (nhân) về cơ bản là để thực hiện phép nhân Quaternion trước, vì vậy xử dựng Quaternion để xoay, và sau đó trích xuất phần vectơ ảo của nó.


In [4]:
def ch_qmulv(q, vin):
    qi = np.concatenate([[0], vin])
    qo = ch_qmul(ch_qmul(q,qi),ch_qconj(q))
    vout = qo[1:]
    return vout

In [7]:
# Test 1: b2n conversion
Qb2n = np.array([0.919, 0.262,  -0.09, -0.282])

# accReading: Giá trị đọc được khi gia tốc kế ở trạng thái nghỉ.
# tương đương với giá trị gia tốc tĩnh trong hệ thống b (vectơ ba chiều trong hệ thống b)
accReading = np.array([0.018, 0.531,  0.843])

Cb2n = ch_q2m(Qb2n)
Gn = Cb2n.dot(accReading)

# Gia tốc của hệ b được chuyển đổi sang hệ n thông qua phép Cb2n
print("Eg1: Acceleration of the b system is transferred to the n Cb2n, the result: %.3f %.3f %.3f \n" %(Gn[0], Gn[1], Gn[2]))
# Kết quả gần bằng 0 0 1

Gn = ch_qmulv(Qb2n, accReading)
# Dùng Quaternion
print("Eg2: Use Quaternion to accReading, get the same result: %.3f %.3f %.3f \n" %(Gn[0], Gn[1], Gn[2]))

# Test 2: n2b conversion
Gn = np.array([0, 0, 1])
# Gn: Ở trạng thái nghỉ, giá trị gia tốc trong hệ N (bằng trọng lực, ngược chiều)
Qn2b = ch_qconj(Qb2n)
Cn2b = ch_q2m(Qn2b)

accB = Cn2b.dot(Gn)

# Gia tốc của hệ n được chuyển đổi sang hệ b thông qua phép Cn2b
print("Eg1: transferred to the b Cn2b, the result: %.3f %.3f %.3f" %(accB[0], accB[1], accB[2]))
print("accReading: %.3f %.3f %.3f\n" %(accReading[0], accReading[1], accReading[2]))

accB = ch_qmulv(Qn2b, Gn)
# Dùng Quaternion rotation function
print("Eg2: Using the Quaternion rotation function, get the same result: %.3f %.3f %.3f \n" %(accB[0], accB[1], accB[2]))

Eg1: Acceleration of the b system is transferred to the n Cb2n, the result: 0.001 0.001 0.997 

Eg2: Use Quaternion to accReading, get the same result: 0.001 0.001 0.997 

Eg1: transferred to the b Cn2b, the result: 0.018 0.532 0.847
accReading: 0.018 0.531 0.843

Eg2: Using the Quaternion rotation function, get the same result: 0.018 0.532 0.847 



Thử nghiệm này có thể nâng cao một chút, khái niệm gia tốc được giới thiệu. Đọc giá trị gia tốc của cảm biến ở trạng thái tĩnh là vectơ tương đương hệ b và trọng lực lý thuyêt tương đương hệ n là [0 0 1]. Chỉ cần nghĩ chúng như là vectơ 3D thông thường.

Tóm tắt:
- Quaternion không phải là một cái gì đó nâng cao, về bản chất nó là một biểu thức đơn giản hóa khác của mảng Attitude, vì vậy tất cả các thuộc tính và mảng Attitude đều giống nhau.
- Có hai định nghĩa về Quaternion: Hamilton và JPL. Loạt bài này sẽ luôn sử dụng Hamilton.
- Chỉ có Quaternion đơn vị mới có thể đại diện cho các tư thế. Trong lĩnh vực điều hướng, nói chung, mặc định Quaternion là Quaternion đơn vị.
- Việc chuyển đổi giữa góc Quaternion và góc Euler sẽ không được đăng ở đây, vì liên quan đến trình tự xoay và nó sẽ phức tạp hơn. Nếu bạn muốn tránh rắc rối, trước tiên bạn có thể chuyển nó thành mảng Attitude, sau đó sử dụng mảng Attitude để chuyển đổi góc Euler.