[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/SlimeVRX/SlimeVRX/blob/main/hipnuc/02.ipynb)

## Study [Attitude determination for IMU & AHRS](https://zhuanlan.zhihu.com/p/351596374) 
#**Lesson 03: 3D rotation.**

Hãy nhớ công thức quay 2D của b2i (ma trận chuyển tọa độ từ hệ b sang hệ i) trong bài trước:

<p align="left"><img width="207", src="https://www.zhihu.com/equation?tex=C%5E%7Bi%7D_%7Bb%7D+%3D+%5Cleft%5B%5Cbegin%7Barray%7D%7Bcc%7D+%5Ccos+%5Cvarphi+%26+-%5Csin+%5Cvarphi+%5C%5C+%5Csin+%5Cvarphi+%26+%5Ccos+%5Cvarphi+%5Cend%7Barray%7D%5Cright%5D"></p>

Phép quay ba chiều có thể hiểu là quay hai chiều, trong không gian ba chiều trục quay nào cũng có thể quay được, trong bài này ta chỉ xét đến phép quay quanh các trục X, Y, Z.

Ma trận chuyển đổi tọa độ để quay quanh trục Z:

<p align="left"><img width="207", src="https://pic2.zhimg.com/80/v2-cf4cdeea2048b712d017e2dc54b53399_720w.jpg"></p>

Ma trận chuyển đổi tọa độ để quay quanh trục Y:

<p align="left"><img width="207", src="https://pic3.zhimg.com/80/v2-11eab02fda4d0f35fd6dcb0070b29afa_720w.jpg"></p>


Ma trận chuyển đổi tọa độ để quay quanh trục X:

<p align="left"><img width="207", src="https://pic1.zhimg.com/80/v2-18b95dd02920179695a1420b0566f908_720w.jpg"></p>

Trong không gian 3D, chuyển động quay quanh một trục cố định được gọi là chuyển động quay sơ cấp Givens, bất kỳ chuyển động quay nào trong không gian đều có thể được tổng hợp bởi ba phép quay cơ bản này.

In [1]:
import numpy as np

cos = np.cos
sin = np.sin
pi = np.pi

In [2]:
def ch_rotx(i):
    theta = pi * i / 180
    return np.array([[1, 0, 0],
                     [0, cos(theta), -sin(theta)], 
                     [0, sin(theta), cos(theta)]])

def ch_roty(i):
    theta = pi * i / 180
    return np.array([[cos(theta), 0, sin(theta)], 
                     [0, 1, 0], 
                     [-sin(theta), 0, cos(theta)]])

def ch_rotz(i):
    theta = pi * i / 180
    return np.array([[cos(theta), -sin(theta), 0], 
                     [sin(theta), cos(theta), 0], 
                     [0, 0, 1]])

In [3]:
i = 30
Cb2nX = ch_rotx(i)
print("Rotate around the X axis %.1f ° the rotation matrix of Cb2nX:\n" %(i), Cb2nX)

i = 40
Cb2nY = ch_roty(i)
print("Rotate around the Y axis %.1f ° the rotation matrix of Cb2nY:\n" %(i), Cb2nY)

i = 50
Cb2nZ = ch_rotz(i)
print("Rotate around the Z axis %.1f ° the rotation matrix of Cb2nZ:\n" %(i), Cb2nZ)

Rotate around the X axis 30.0 ° the rotation matrix of Cb2nX:
 [[ 1.         0.         0.       ]
 [ 0.         0.8660254 -0.5      ]
 [ 0.         0.5        0.8660254]]
Rotate around the Y axis 40.0 ° the rotation matrix of Cb2nY:
 [[ 0.76604444  0.          0.64278761]
 [ 0.          1.          0.        ]
 [-0.64278761  0.          0.76604444]]
Rotate around the Z axis 50.0 ° the rotation matrix of Cb2nZ:
 [[ 0.64278761 -0.76604444  0.        ]
 [ 0.76604444  0.64278761  0.        ]
 [ 0.          0.          1.        ]]


Chuyển một điểm tọa độ A trong hệ b sang hệ n thông qua các ma trận sau:

In [8]:
Ab = np.array([0, 0, 1])

print("point A belongs to the coordinate b system:\n", Ab)

An = ch_rotx(30).dot(Ab)
print("The point A belongs to the coordinate b system is rotated to the n system by Cb2nX:\n", An)

An = ch_roty(40).dot(Ab)
print("The point A belongs to the coordinate b system is rotated to the n system by Cb2nY: \n", An)

An = ch_rotz(50).dot(Ab)
print("The point A belongs to the coordinate b system is rotated to the n system by Cb2nZ: \n", An)

point A belongs to the coordinate b system:
 [0 0 1]
The point A belongs to the coordinate b system is rotated to the n system by Cb2nX:
 [ 0.        -0.5        0.8660254]
The point A belongs to the coordinate b system is rotated to the n system by Cb2nY: 
 [0.64278761 0.         0.76604444]
The point A belongs to the coordinate b system is rotated to the n system by Cb2nZ: 
 [0. 0. 1.]


Nâng cao:

Hãy thay đổi góc quay của các ma trận thành -90 °, rồi chuyển điểm A [0,0,1] trong hệ thống b qua ba ma trận Cb2n được quay -90 ° để nhận kết quả

Sau đó di chuyển bút một lần nữa, xoay nó theo cách thủ công trong tâm trí của bạn và so sánh xem kết quả của phép tính thủ công có phù hợp với kết quả của Python hay không. Thông qua bài này, bạn sẽ hiểu sâu hơn về phép biến đổi ma trận cơ bản 3D.

In [22]:
Ab = np.array([1, 0, 0])

print("point A belongs to the coordinate b system:\n", Ab)


An = ch_roty(-90).dot(Ab)
print("The point A belongs to the coordinate b system is rotated to the n system by Cb2nY: \n", An)

An = ch_rotx(-90).dot(An)
print("The point A belongs to the coordinate b system is rotated to the n system by Cb2nX:\n", An)

An = ch_rotz(-90).dot(An)
print("The point A belongs to the coordinate b system is rotated to the n system by Cb2nZ: \n", An)

#ch_rotz(-90).dot(ch_rotx(-90).dot(ch_roty(-90).dot(Ab)))

point A belongs to the coordinate b system:
 [1 0 0]
The point A belongs to the coordinate b system is rotated to the n system by Cb2nY: 
 [6.123234e-17 0.000000e+00 1.000000e+00]
The point A belongs to the coordinate b system is rotated to the n system by Cb2nX:
 [6.123234e-17 1.000000e+00 6.123234e-17]
The point A belongs to the coordinate b system is rotated to the n system by Cb2nZ: 
 [1.000000e+00 0.000000e+00 6.123234e-17]


Tóm tắt và Khuyến nghị:

1. Ma trận chuyển đổi tọa độ từ hệ tọa độ b sang hệ tọa độ n được ký hiệu là b2n, hoặc b->n hoặc

<p align="left"><img width="25", src="https://www.zhihu.com/equation?tex=C%5E%7Bn%7D_%7Bb%7D"></p>

2. Phải thành thạo phép quay sơ cấp 3D (Givens), đặc biệt chỉ ra rằng phép quay trong bài này được hiểu là ma trận biến đổi tọa độ chuyển điểm tọa độ từ hệ b sang hệ n (b2n). Trong các sách thông tin khác, bạn có khả năng nhìn thấy các ma trận quay sơ cấp khác nhau, điều này là do định nghĩa của mọi người khác nhau, một số có thứ tự n2b, bạn rất dễ bị chóng mặt khi lần đầu tiên tiếp xúc với chúng.

3. Bạn nên xây dựng hàm thư viện Python của riêng mình từ bây giờ và biến rotx roty rotz thành hàm thư viện Python của riêng bạn, để bạn có thể lưu trữ và tinh chỉnh những gì bạn đã học. Và cũng hình thành “ổ khóa” hay cảm giác an toàn cho những kiến ​​thức đã học.